<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN900BJb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN900BJb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN900BJb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN900BJb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN900BJb\App_KernelDevDebugContainer([
    'container.build_hash' => 'N900BJb',
    'container.build_id' => '6b003339',
    'container.build_time' => 1606994471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN900BJb');
