<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'City_index' => [[], ['_controller' => 'App\\Controller\\CityController::index'], [], [['text', '/City/']], [], []],
    'City_new' => [[], ['_controller' => 'App\\Controller\\CityController::new'], [], [['text', '/City/new']], [], []],
    'City_show' => [['id'], ['_controller' => 'App\\Controller\\CityController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/City']], [], []],
    'City_edit' => [['id'], ['_controller' => 'App\\Controller\\CityController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/City']], [], []],
    'City_delete' => [['id'], ['_controller' => 'App\\Controller\\CityController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/City']], [], []],
    'find_City_by_name' => [['name'], ['_controller' => 'App\\Controller\\CityController::findAllByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/City/find']], [], []],
    'Country_index' => [[], ['_controller' => 'App\\Controller\\CountryController::index'], [], [['text', '/Country/']], [], []],
    'Country_new' => [[], ['_controller' => 'App\\Controller\\CountryController::new'], [], [['text', '/Country/new']], [], []],
    'find_Country_by_name' => [['name'], ['_controller' => 'App\\Controller\\CountryController::findAllByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/Country/find']], [], []],
    'Country_show' => [['id'], ['_controller' => 'App\\Controller\\CountryController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Country']], [], []],
    'Country_edit' => [['id'], ['_controller' => 'App\\Controller\\CountryController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/Country']], [], []],
    'Country_delete' => [['id'], ['_controller' => 'App\\Controller\\CountryController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Country']], [], []],
];
