<?php

namespace ContainerN900BJb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O5pmaFWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O5pmaFW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O5pmaFW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Country' => ['privates', '.errored..service_locator.O5pmaFW.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.O5pmaFW": it references class "App\\Entity\\Country" but no such service exists.'],
        ], [
            'Country' => 'App\\Entity\\Country',
        ]);
    }
}
