<?php

namespace ContainerN900BJb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XE5VphService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xE5Vph_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xE5Vph_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CityController::delete' => ['privates', '.service_locator.QCoKGVo', 'get_ServiceLocator_QCoKGVoService', true],
            'App\\Controller\\CityController::edit' => ['privates', '.service_locator.QCoKGVo', 'get_ServiceLocator_QCoKGVoService', true],
            'App\\Controller\\CityController::findAllByName' => ['privates', '.service_locator.q0ws5Av', 'get_ServiceLocator_Q0ws5AvService', true],
            'App\\Controller\\CityController::index' => ['privates', '.service_locator.q0ws5Av', 'get_ServiceLocator_Q0ws5AvService', true],
            'App\\Controller\\CityController::show' => ['privates', '.service_locator.QCoKGVo', 'get_ServiceLocator_QCoKGVoService', true],
            'App\\Controller\\CountryController::delete' => ['privates', '.service_locator.O5pmaFW', 'get_ServiceLocator_O5pmaFWService', true],
            'App\\Controller\\CountryController::edit' => ['privates', '.service_locator.O5pmaFW', 'get_ServiceLocator_O5pmaFWService', true],
            'App\\Controller\\CountryController::findAllByName' => ['privates', '.service_locator.CaoVTkF', 'get_ServiceLocator_CaoVTkFService', true],
            'App\\Controller\\CountryController::index' => ['privates', '.service_locator.CaoVTkF', 'get_ServiceLocator_CaoVTkFService', true],
            'App\\Controller\\CountryController::show' => ['privates', '.service_locator.O5pmaFW', 'get_ServiceLocator_O5pmaFWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CityController:delete' => ['privates', '.service_locator.QCoKGVo', 'get_ServiceLocator_QCoKGVoService', true],
            'App\\Controller\\CityController:edit' => ['privates', '.service_locator.QCoKGVo', 'get_ServiceLocator_QCoKGVoService', true],
            'App\\Controller\\CityController:findAllByName' => ['privates', '.service_locator.q0ws5Av', 'get_ServiceLocator_Q0ws5AvService', true],
            'App\\Controller\\CityController:index' => ['privates', '.service_locator.q0ws5Av', 'get_ServiceLocator_Q0ws5AvService', true],
            'App\\Controller\\CityController:show' => ['privates', '.service_locator.QCoKGVo', 'get_ServiceLocator_QCoKGVoService', true],
            'App\\Controller\\CountryController:delete' => ['privates', '.service_locator.O5pmaFW', 'get_ServiceLocator_O5pmaFWService', true],
            'App\\Controller\\CountryController:edit' => ['privates', '.service_locator.O5pmaFW', 'get_ServiceLocator_O5pmaFWService', true],
            'App\\Controller\\CountryController:findAllByName' => ['privates', '.service_locator.CaoVTkF', 'get_ServiceLocator_CaoVTkFService', true],
            'App\\Controller\\CountryController:index' => ['privates', '.service_locator.CaoVTkF', 'get_ServiceLocator_CaoVTkFService', true],
            'App\\Controller\\CountryController:show' => ['privates', '.service_locator.O5pmaFW', 'get_ServiceLocator_O5pmaFWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CityController::delete' => '?',
            'App\\Controller\\CityController::edit' => '?',
            'App\\Controller\\CityController::findAllByName' => '?',
            'App\\Controller\\CityController::index' => '?',
            'App\\Controller\\CityController::show' => '?',
            'App\\Controller\\CountryController::delete' => '?',
            'App\\Controller\\CountryController::edit' => '?',
            'App\\Controller\\CountryController::findAllByName' => '?',
            'App\\Controller\\CountryController::index' => '?',
            'App\\Controller\\CountryController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CityController:delete' => '?',
            'App\\Controller\\CityController:edit' => '?',
            'App\\Controller\\CityController:findAllByName' => '?',
            'App\\Controller\\CityController:index' => '?',
            'App\\Controller\\CityController:show' => '?',
            'App\\Controller\\CountryController:delete' => '?',
            'App\\Controller\\CountryController:edit' => '?',
            'App\\Controller\\CountryController:findAllByName' => '?',
            'App\\Controller\\CountryController:index' => '?',
            'App\\Controller\\CountryController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
