<?php

namespace ContainerN900BJb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CaoVTkFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CaoVTkF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CaoVTkF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'CountryRepository' => ['privates', 'App\\Repository\\CountryRepository', 'getCountryRepositoryService', true],
        ], [
            'CountryRepository' => 'App\\Repository\\CountryRepository',
        ]);
    }
}
