<?php

namespace ContainerN900BJb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O5pmaFW.App\Entity\Country' shared service.
     *
     * @return \App\Entity\Country
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.O5pmaFW": it references class "App\\Entity\\Country" but no such service exists.');
    }
}
